### ISSUE TITLE
pypitest vs testpypi

### ISSUE THREAD

**Issue by svenevs** [jonemo/neubertify#1]
Hey Jonas!

Your [`twine upload` instructions](https://github.com/jonemo/neubertify/blob/gh-pages/_posts/2017-09-13-publishing-your-first-pypi-package.md#step-4-use-twine-to-upload-your-package) don't match the `.pypirc` file (`pypitest` vs `testpypi`) :wink:

Great post!  You should link to the [`pypa/readme_renderer`](https://github.com/pypa/readme_renderer) tool, it was the only thing that actually told me why my PyPI long description was broken.  You're followup on that other issue reminded me that I wanted to link it, the PR just got merged and it's in Tip for the [packaging tutorial](https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi) now.

Added this here because I didn't want to clutter that issue anymore than I already had...

-Stephen

**Comment by jonemo** [comment]
> Your [`twine upload` instructions](https://github.com/jonemo/neubertify/blob/gh-pages/_posts/2017-09-13-publishing-your-first-pypi-package.md#step-4-use-twine-to-upload-your-package) don't match the `.pypirc` file (`pypitest` vs `testpypi`)

🦅 👀 !

Fixed in https://github.com/jonemo/neubertify/commit/137a1669fc0115c48ef456414eb5700b877b359a

**Comment by jonemo** [comment]
As for the second part about `readme_renderer`: Good point, I'll add it to my notes for a potential future blog posts about "PyPI gotchas". 

Note to self: The documentation change is in this commit: https://github.com/pypa/python-packaging-user-guide/commit/5eb8f2bc0b46c35d7abbeafa16c8e2f8f577ac31
